config/routes.rb
Rails.application.routes.draw do
  resources :trees

  root 'trees#index'
  
  get '/contact' => 'static_pages#contact'
  post '/contact' => 'static_pages#sendmail'
  

end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :tree
  
  def to_s
    return "id: " + self.relative_id.to_s +
			", x: " + self.x.to_s +
			", y: " + self.y.to_s +
			", pos: \"" + self.part_of_speech.to_s +
			"\", contents: \"" + self.contents.to_s +
			"\", theta: " + self.theta.to_s +
			", caseMarker: " + self.case_marker.to_s +
			", showContent: " + self.show_content.to_s +
			", showTriangle: " + self.show_triangle.to_s
  end
end

app/models/trace.rb
class Trace < Node
  def to_s
    return super.to_s + 
	        ", traceIdx: \"" + trace_idx.to_s + "\""
  end
end

app/models/tree.rb
require "seed_exceptions"

class Tree < ActiveRecord::Base
	has_many :nodes
	
	def root
		root = nodes.where(pid: nil)
		if root.length > 1
			raise Seed::TreeError, "There should be exactly one root, not #{root.length}."
		elsif root.length == 0
			return nil
		end
		
		return root[0]
	end
	
	def leaf? (node)
		return (not nodes.exists?(pid: node.relative_id))
	end
	
	def children (node)
		return nodes.where(pid: node.relative_id).order(:x)
	end
	
	def node_str (node)
		if node.nil?
			return ''
		end
	
		res = '[' + node.part_of_speech
		if self.leaf?(node)
			# Normal node; add contents and potential trace identifier
			if node.type == 'Node' and not (node.contents.nil? or node.contents.empty?)
				res += ' ' + node.contents
				trace = nodes.find_by(relative_id: node.trace_id)
				if not trace.nil?
					res += '_' + trace.trace_idx
				end
			else # Trace; add trace identifier
				res += ' t_' + node.trace_idx
			end
		else
			children = self.children(node)
			if not children.empty?
				res += ' '
			end
			children.each do |child|
				res += self.node_str(child)
			end
		end
		
		return res + ']'
	end
	
	def export_txt
		return self.node_str(self.root)
	end
	
	def parse_node (src, pid, next_node_id)
		
		match_pos = src.match(/^\[\s*(\w*)\s*/)
		node = Node.new
		node.relative_id = next_node_id
		node.pid = pid
		node.type = 'Node'
		node.part_of_speech = match_pos[1]

		node.x = 0
		node.y = 0

		node.theta = false
		node.case_marker = false
		
		node.show_content = false
		node.show_triangle = false

		if src[match_pos.end(0)] == '['
			self.nodes << node

			start = match_pos.end(0)
			new_subtree = true
			for i in (start..src.length - 2) #Ignore the last closing bracket
				if src[i] == '['
					if new_subtree
						start = i 
						balance = 1
						new_subtree = false
					else
						balance += 1
					end
				elsif src[i] == ']'
					balance -= 1
					if balance == 0
						# Process this sub-tree
						next_node_id += self.parse_node(src.slice((start..i)), node.relative_id, next_node_id + 1)
						new_subtree = true
					elsif balance < 0
						raise Seed::TreeParseError, "Unmatched bracket"
					end
				end
			end
			
			if balance > 0
				raise Seed::TreeParseError, "Unmatched bracket"
			end
			return next_node_id

		else # This is normally a leaf
			# Obtain the contents
			match_contents = src[match_pos.end(0), src.length - match_pos.end(0)].match(/(.*)\]/)
			if match_contents.nil?
				raise Seed::TreeParseError, "Unmatched bracket"
			end
			
			if match_contents[1].include? "[" or match_contents[1].include? "]"
				raise Seed::TreeParseError
			end
			
			node.contents = match_contents[1]
			node.show_content = true
			self.nodes << node

			return 1
		end

	end

	def parse_txt (src)
		src.rstrip!
		src.lstrip!
		
		# Parsing nothing is a no-op
		if src.empty?
			return
		end
		
		match_data = src.match(/^\[(.)*\]$/)
		if not match_data.nil?
			self.parse_node(match_data[0], nil, 0)
		else
			raise Seed::TreeParseError, "Parse error"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def sendmail
		Contact.contact(form_params[:source], form_params[:content])
		render "contact_end"
	end
	
	private
		def form_params
			params.require(:contact).permit(:source, :content)
		end

end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
	
	#List the user's trees
	def index
		if cookies[:seed_id].nil?
			cookies.permanent[:seed_id] = get_new_id
		else
			@trees = Tree.where(uid: cookies[:seed_id])
		end
	end
	
	# Show the form for creating a new tree
	def new
	end
	
	# Actual creation of the tree
	def create
		@tree = Tree.new
		@tree.name = tree_params[:name]
		@tree.uid = cookies[:seed_id]
		session[:import] = false
		
		if not (tree_params[:brackets].nil? or tree_params[:brackets].empty?)
			@tree.parse_txt(tree_params[:brackets])
			session[:import] = true
		end
		@tree.save
		redirect_to @tree
	end
	
	# Show the tree itself
	def show
		@tree = Tree.find(params[:id])
		@import = session[:import]
		session[:import] = nil
		respond_to do |format|
			format.html
			format.txt { render plain: @tree.export_txt }
		end
	end
	
	# Update (save) the tree
	def update
		# TODO Validation around here
		params[:tree].each do |node_json|
			begin
				node_obj = Node.find_by!(tree_id: params[:id], relative_id: node_json['id'])				
			rescue
				node_obj = Node.new
				node_obj.tree_id = params[:id]
				node_obj.relative_id = node_json['id']
			end
			
			#TODO Change json names so that they reflect what's in the database
			node_obj.part_of_speech = node_json['pos']
			
			node_obj.x = node_json['x']
			node_obj.y = node_json['y']
			node_obj.pid = node_json['pid']
			
			node_obj.case_marker = node_json['case']
			node_obj.theta = node_json['theta']
			
			node_obj.type = node_json['type']
			if node_json['type'] == 'Node'
				node_obj.contents = node_json['content']
				node_obj.trace_id = node_json['trace_id']
				node_obj.show_content = node_json['show_content']
				node_obj.show_triangle = node_json['show_triangle']
			else
				node_obj.trace_idx = node_json['trace_idx']
				node_obj.show_content = false
				node_obj.show_triangle = false
			end
			
			node_obj.save
		end
		
		if not params[:del].nil?
			params[:del].each do |node|
				to_delete = Node.find_by(tree_id: params[:id], relative_id: node)
				if not to_delete.nil?
					to_delete.delete
				end
			end
		end
		
		
		render json: {status => 0}
	end
	
	private
		def tree_params
			params.require(:tree).permit(:name, :brackets)
		end
		
		def get_new_id
			begin
				id_file = File.open (Rails.root + "userid/userid.txt"), "r"
				id = id_file.read.to_i
				id_file.close
			rescue
				id = 0
			end

			id_file = File.open (Rails.root + "userid/userid.txt"), "w"
			id_file.write (id + 1).to_s
			id_file.close
			
			return id
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/contact/contact.text.erb
Message from <%= @src_email %>
Sent at <%= Time.now %>
========================

<%= @contact_text %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seed</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/trees.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seed</title>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
  
  <%= javascript_include_tag 'application' %>
  
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p style="max-width: 500px">
If you have any questions, requests or problems, please send an email to
<a href="mailto:fred@lafrancef.net">fred@lafrancef.net</a> to contact the 
developer of the application. Make sure to include as many details as you 
can, especially if you wish to report a bug with the application.
</p>

<!--
<%= form_tag do %>
<p>
	<label for="contact_source">Your email</label>:
	<%= text_field "contact", "source" %>
</p>
<p>
	<label for="contact_content">Your message</label>:<br/>
	<%= text_area "contact", "content" %>
</p>
<%= submit_tag "Send" %>
<% end %>

-->

app/views/static_pages/contact_end.html.erb
<h1>Contact</h1>

<p>Thank you for your feedback!</p>

app/views/trees/_edit_tree.js.erb
var NODES = {};
var EDITED; //Currently edited node
var SAVER;
var ID_COUNTER = 0;
var MAX_TRACE_ID = "i";

var KinSTAGE;
var KinLAYER;

var clickedLine = false; //Hack!

function asNode(that) {
	return NODES[$(that).data("id")];
}

//TODO Try to remove magic numbers throughout the code

/* Execute a function on all the nodes in the tree. If func is a function name, a method of Node
will be called. If func is a function, the function will be called with a reference
to each node (stopping if func returns false). If filter is a function, the function is passed
the nodes in turn, and func is called with them only if filter returns true. */
function allNodes(func, filter) {
	for(id in NODES) {
		if(typeof filter === "function") {
			if(!filter(NODES[id])) continue;
		}
	
		var fn = NODES[id][func];
		if(typeof NODES[id][func] === "function") {
			if(NODES[id][func]() === false)
				break;
		} else if(typeof func === "function") {
			if(func(NODES[id]) === false)
				break;
		} else {
			throw new Error("allNodes: first parameter must be either a function or a method of Node");
		}
	}
}

function allSelectedNodes(func) {
	allNodes(func, function(node) {
		return node.isSelected();
	});
}

function allSelectedLines(func) {
	allNodes(func, function(node) {
		return node.lineSelected();
	});
}

function allTraces(func) {
	allNodes(func, function(node) {
		return (node instanceof Trace);
	});
}

function clickLine(e) {
	var possessingNode = NODES[this.id()];
	clickedLine = true;
	
	if(e.evt.shiftKey == false) {
		/* No shift key: 
			- Deselect everything
			- Select this element if it was not selected, or if
			  it was part of a multi-selection
		*/
		
		allSelectedNodes("deselect");
		
		var numSel = 0;
		allSelectedLines(function(node) {
			if(node.lineSelected())
				numSel++;
		});
		
		var wasSelected = possessingNode.lineSelected();
		allSelectedLines("deselectLine");
	
		if(!wasSelected || numSel > 1)
			possessingNode.selectLine();
    } else {
		if(possessingNode.lineSelected())
			possessingNode.deselectLine();
		else
			possessingNode.selectLine();
    }
	
	KinSTAGE.draw();
}

function offsetTo10s(num) {
	var r = num % 10;
	if(r < 5)
		return r; //Round down
	else
		return -10 + r; //Round up
}

function nonOverlappingPosition(left, top) {
	var positionFound = false;
	while(!positionFound) {
		// Check all nodes to see if current top/left overlaps with one of them
		var overlaps = false;
		allNodes(function(node) {
			var topLeft = node.getTopLeft();
			//Minimal "non-overlap" distance is 6 (because of the 10x10 grid)
			if(Math.abs(topLeft.left - left) <= 5 && 
					Math.abs(topLeft.top - top) <= 5) {
				overlaps = true;
				return false; //Stop iterating since we found an overlapping node
			}
		});
		
		//If current position overlaps, shift to the right.
		if(!overlaps)
			positionFound = true;
		else
			left += 40;
	}
	
	return {top: top, left: left};
}

var middle = function(n) {
	if(n - Math.floor(n) > 0)
		return n;
	else
		return n + 0.5;
}

function updateMainCanvasHeight() {
	var menu = document.getElementById("operationsMenuOuter");
	//25: arbitrary margin at the bottom
	var available = window.innerHeight - menu.getBoundingClientRect().bottom - 25;
	
	$("#mainCanvas").css("height", available + "px");
}

function maybeResizeCanvas(node) {
	var RESIZE_MARGIN = 5, RESIZE_BUFFER = 100;
	var maxRight = -1, maxBottom = -1;
	var w = KinSTAGE.width(), h = KinSTAGE.height();
	
	if(node == undefined) {
		allNodes(function(n) {
			var right = n.getDimensions().x + n.getTopLeft().left;
			if(right > maxRight)
				maxRight = right;
				
			var bottom = n.getDimensions().y + n.getTopLeft().top;
			if(bottom > maxBottom)
				maxBottom = bottom;
		});
	} else {
		maxRight = node.getDimensions().x + node.getTopLeft().left;
		maxBottom = node.getDimensions().y + node.getTopLeft().top;
	}

	if(maxRight + RESIZE_MARGIN > w)
		KinSTAGE.width(maxRight + RESIZE_BUFFER);
		
	if(maxBottom + RESIZE_MARGIN > h)
		KinSTAGE.height(maxBottom + RESIZE_BUFFER);
}

$(window).load(function(){

updateMainCanvasHeight();

$(window).resize(updateMainCanvasHeight);

$mainCanvas = $( "#mainCanvas" );
var mainCanvas = document.getElementById("mainCanvas");
var mainCanvasPos = mainCanvas.getBoundingClientRect();

KinSTAGE = new Kinetic.Stage({container: "mainCanvas", height: $(mainCanvas).height() - 10, width: $(mainCanvas).width() - 10, listening: true});
KinLAYER = new Kinetic.Layer({listening: true});
KinSTAGE.add(KinLAYER);

$mainCanvas.selectable({
	/* Require a distance to activate selection. This is because we
	want to override normal clicks. */
	distance: 1,
	filter: ".node", //Only select nodes (i.e. don't select KineticJS elements)
	start: function(e, ui) {
		if(EDITED != undefined)
			EDITED.stopEditing();
	}
}).click(function(e){
	/* If we get here, it means we did not click on a child
	div. Therefore, deselect everything. */		
	if(!e.shiftKey && !clickedLine) {
		allNodes("deselect");
		allSelectedLines("deselectLine");
			
		KinSTAGE.draw();
	}

	clickedLine = false;
	
	if (EDITED != undefined)
		EDITED.stopEditing();
		
}).dblclick(function(e) {

	var x = e.pageX - mainCanvasPos.left;
	var y = e.pageY - mainCanvasPos.top;

	NODES[ID_COUNTER] = new Node({id: ID_COUNTER, x: x, y: y, showContent: true, showTriangle: false});
	ID_COUNTER += 1;
	
	$(mainCanvas).selectable("refresh");
});

$(document.body).keydown(function(e) {
	if(e.keyCode == 46) { //Delete key
		if (EDITED == undefined) {
			allSelectedNodes("remove");
			allSelectedLines("removeLine");
		}
	} else if(e.keyCode == 27) { //Escape key
		allNodes("deselect");
		allNodes("deselectLine");
		if (EDITED != undefined)
			EDITED.stopEditing();
	}
});

$("#btnAdd").click(function() {	
	var node = new Node({id: ID_COUNTER, x: 10, y: 10});
	NODES[ID_COUNTER] = node;
	ID_COUNTER += 1;	
	var pos = nonOverlappingPosition(($mainCanvas.outerWidth() - node.getDimensions().x) / 2, 
									($mainCanvas.outerHeight() - node.getDimensions().y) / 2);
	node.move(pos.left, pos.top);

	$(mainCanvas).selectable("refresh");	
});

$("#btnCreateChild").click(function() {
	allSelectedNodes( function(n) { 
		if (n instanceof Node) {
			// Spawn node on first select child only
			n.spawnChild(false);
			return false;
		}
	});
});

$("#btnTrace").click(function() {

	allSelectedNodes( function(n) { 
		if (n instanceof Node) {
			// Spawn node on first select child only
			n.spawnChild(true);
			return false;
		}
	});
});

$("#btnPretty").click(function() {

	allSelectedNodes( function(n) { 
		n.prettify(false);
		n.prettyPosition(true);
		return false;
	});
});

$("#btnSave").click(function() {
	SAVER.saveTree();
});

$("#btnTheta").click(function() {
	allSelectedNodes("toggleTheta");
});

$("#btnCase").click(function() {
	allSelectedNodes("toggleCase");
});

$("#btnContent").click(function() {
	allSelectedNodes(function(n) {
		if(n instanceof Node && n.isLeaf())
			n.toggleContent();
	});
});

$("#btnTriangle").click(function() {
	allSelectedNodes(function(n) {
		if(n instanceof Node)
			n.toggleTriangle();
	});
});

$("#btnLink").click(function() {
	var sel1, sel2;
	
	// Pick the first two selected nodes
	allSelectedNodes(function(n) { 
		if(n.isSelected()) {
			if(sel1 == undefined)
				sel1 = n;
			else {
				sel2 = n;
				return false;
			}
		}
	});
	
	//We need two selected
	if(sel1 == undefined || sel2 == undefined)
		return;
	
	//Can't link two traces
	if(sel1 instanceof Trace && sel2 instanceof Trace)
		return;
	
	if(sel1 instanceof Trace) {
		sel1.linkTracee(sel2.id);
		sel2.linkTrace(sel1.id);
		return;
	}
	
	if(sel2 instanceof Trace) {
		sel1.linkTrace(sel2.id);
		sel2.linkTracee(sel1.id);
		return;
	}
		
	if(!sel1.hasParent() && !sel2.hasParent()) {
		//If neither has a parent, the one that's higher in the page will get to be the parent
		if(sel1.getCanvasRelativeCenter().y < sel2.getCanvasRelativeCenter().y)
			sel1.linkNewChild(sel2.id)
		else
			sel2.linkNewChild(sel1.id)
	
	} else if (sel1.hasParent() && sel2.hasParent()) {
		//If both have parents, we can't link them together
		return; //TODO have feedback here
	} else if (sel1.hasParent()) {
		//If only one has a parent, then that one becomes the parent of the other
		//(since the reverse is impossible)
		sel1.linkNewChild(sel2.id)
	} else if (sel2.hasParent()) {
		sel2.linkNewChild(sel1.id)
	}
});

var wasImported = loadTree();
SAVER = new Saver();

if(wasImported) {
	allNodes("signalModification");
}

$(mainCanvas).selectable("refresh");

});

app/views/trees/_nodes.js.erb
Node.prototype = new BasicNode();
Node.prototype.constructor = Node;
Node._TRIANGLE_HEIGHT = 30;
Node._TRIANGLE_BORDER_WIDTH = 2;

function Node(opts) {
	this.basicInit(opts.id, opts.theta, opts.caseMarker);
	this._traceId = undefined;
	this._content = opts.showContent;
	this._triangle = opts.showTriangle;
	
	var node = this.createSkeleton(opts.pos);
	
	var content = document.createElement("span");
	if(opts.contents != undefined)
		content.innerHTML = opts.contents;

	var trace = document.createElement("sub");
	trace.className = "trace";
	
	//The SVG element must be created in one go, otherwise it won't render properly
	this._$triangle = $('<svg xmlns="http://www.w3.org/2000/svg" ' +
						'version="1.1" viewbox="0 0 100 100" ' +
						'preserveaspectratio="none">' +
						'<polygon points="0,98 50,2 100,98" ' +
						'style="fill:white; stroke:black; stroke-width:' +
						Node._TRIANGLE_BORDER_WIDTH + ';"/></svg>');
		
	this._$triangle.css("height", Node._TRIANGLE_HEIGHT + "px")
					.css("width", this._EDIT_MIN_WIDTH + "px")
					.css("display", "block")
					.css("margin", "auto");
					
	var container = document.createElement("div");
	container.appendChild(this._$triangle[0]);
	container.appendChild(content);
	container.appendChild(trace);
	node.appendChild(container);
	
	mainCanvas.appendChild(node);
	
	this._$content = $(content);
	this._$trace = $(trace);
	this._$container = $(container);
	
	this.makeEditable(this._$content, this._EMPTY_CONTENT, 140);
	
	this.updateTriangle();
	this.updateTriangleVisual();
	this.updateContentVisual();
	this.move(opts.x, opts.y);
	if(SAVER != undefined)
		SAVER.signalModification(this.id);
}

Node.prototype.simplify = function() {
	var simple = {
		id: this.id,
		pid: this._pid,
		x: parseInt(this._$node.css("left")),
		y: parseInt(this._$node.css("top")),
		"case": this._case,
		theta: this._theta,
		trace_id: this._traceId,
		type: "Node",
		show_content: this._content,
		show_triangle: this._triangle
	}
	
	if(this._$pos[0].innerHTML != this._EMPTY_POS)
		simple["pos"] = this._$pos[0].innerHTML;
		
	if(this._$content[0].innerHTML != this._EMPTY_CONTENT)
		simple["content"] = this._$content[0].innerHTML;
		
	return simple;
}

Node.prototype.isEditing = function() {
	return (this._$pos.is(":editing") || this._$content.is(":editing"))
}

Node.prototype.stopEditing = function() {
	if(this._$pos.is(":editing"))
		this._$pos.editable("close");
		
	if(this._$content.is(":editing"))
		this._$content.editable("close");
}

Node.prototype.toggleContent = function() {
	this._content = !this._content;
	this.updateContentVisual();
	this.signalModification();
}

Node.prototype.updateContentVisual = function() {
	var oldCenter = this.getCanvasRelativeCenter();
	
	if(this._content)
		this._$container.css("display", "block");
	else
		this._$container.css("display", "none");
		
	this.centerOn(oldCenter.x, oldCenter.y);
	this.hasMoved();
}

Node.prototype.toggleTriangle = function() {
	this._triangle = !this._triangle;
	this.updateTriangleVisual();
	this.signalModification();
}

Node.prototype.updateTriangleVisual = function() {
	if(this._triangle)
		this._$triangle.css("display", "block");
	else
		this._$triangle.css("display", "none");
		
	this.hasMoved();
}

Node.prototype.updateTriangle = function() {
	var w = this._$content.outerWidth();
	if(w >= this._EDIT_MIN_WIDTH)
		this._$triangle.css("width", w + "px");
}

Node.prototype.remove = function() {
	if(this._traceId != undefined)
		NODES[this._traceId].traceeRemoved();
	
	BasicNode.prototype.remove.call(this);
}

Node.prototype.spawnChild = function(isTrace) {
	var center = this.getCanvasRelativeCenter();
	var topLeft = this.getTopLeft();
	
	//TODO use actual border width
	var newNode;
	if(isTrace) {
		newNode = new Trace({id: ID_COUNTER, x: 10, y: 10, traceId: Trace.generateId()});
	} else {
		newNode = new Node({id: ID_COUNTER, x: 10, y: 10, showContent: true, showTriangle: false});
	}
	newNode.setParent(this.id);
	this._chids[newNode.id] = true;
	
	var pos = nonOverlappingPosition(center.x - newNode.getDimensions().x / 2, topLeft.top + 100);
	newNode.move(pos.left, pos.top);

	NODES[ID_COUNTER] = newNode;
	
	ID_COUNTER += 1;
	this.signalModification();
	
	if(this._content)
		this.toggleContent();
	$(mainCanvas).selectable("refresh");
}

Node.prototype.removeChild = function(chid) {
	delete this._chids[chid];
	//Line is taken care of by child
	
	//Show our content if we have no more children
	var count = 0;
	for(chid in this._chids)
		count++;
		
	if(count == 0 && !this._content)
		this.toggleContent();
}

Node.prototype.linkNewChild = function(chid) {
	this._chids[chid] = true;
	NODES[chid].setParent(this.id); //Child signals its modification here
	this.signalModification();
	
	if(this._content)
		this.toggleContent();
}

Node.prototype.linkTrace = function(traceId) {
	this._traceId = traceId;
	this._$trace[0].innerHTML = NODES[traceId].traceId;
	
	this.signalModification();
}

Node.prototype.traceRemoved = function() {
	this._traceId = undefined;
	this._$trace[0].innerHTML = "";
	
	this.signalModification();
}

Trace.prototype = new BasicNode();
Trace.prototype.constructor = Trace;
function Trace(opts) {
	this.basicInit(opts.id, opts.theta, opts.caseMarker);
	this.traceId = opts.traceId;
	this._traceeId = undefined;
	
	var node = this.createSkeleton(opts.pos);
	
	var trace = document.createElement("div");
	trace.innerHTML = "<i>t</i><sub>" + this.traceId + "</sub>";
	
	node.appendChild(trace);
	mainCanvas.appendChild(node);
	
	this.move(opts.x, opts.y);
	if(SAVER != undefined)
		SAVER.signalModification(this.id);
}

Trace.generateId = function() {
	
	var maxId = MAX_TRACE_ID.charCodeAt(0);
	var start = "i".charCodeAt(0);
	
	var ids = [];
	allTraces(function(tr) {
		ids[tr.traceId.charCodeAt(0) - start] = true;
	});
	
	for(i = 0 ; i <= (maxId - start) ; i++) {
		if(ids[i] === undefined)
			return String.fromCharCode(i + start);
	}
	
	MAX_TRACE_ID = String.fromCharCode(maxId + 1);
	return MAX_TRACE_ID;
}

Trace.prototype.simplify = function() {
	var simple = {
		id: this.id,
		pid: this._pid,
		x: parseInt(this._$node.css("left")),
		y: parseInt(this._$node.css("top")),
		trace_idx: this.traceId,
		"case": this._case,
		theta: this._theta,
		type: "Trace"
	}
	
	if(this._$pos[0].innerHTML != this._EMPTY_POS)
		simple["pos"] = this._$pos[0].innerHTML;
		
	return simple;
}

Trace.prototype.isEditing = function() {
	return this._$pos.is(":editing");
}

Trace.prototype.stopEditing = function() {
	if(this._$pos.is(":editing"))
		this._$pos.editable("close");
}

Trace.prototype.remove = function() {
	if(this._traceeId != undefined)
		NODES[this._traceeId].traceRemoved();
	
	BasicNode.prototype.remove.call(this);
}

Trace.prototype.linkTracee = function(traceeId) {
	this._traceeId = traceeId;
	
	this.signalModification();
}

Trace.prototype.traceeRemoved = function() {
	this._traceeId = undefined;
}

app/views/trees/index.html.erb
<h1>Seed - Your trees</h1>

<% if @trees.nil? %>
	<p>You have no trees yet.</p>
<% else %>
	<p>
		<ul>
			<% @trees.each do |tree| %>
			<li>
				<%= link_to tree.name, tree%>
			</li>
			<% end %>
		</ul>
	</p>
<% end %>

<p>Click <%= link_to 'here', new_tree_path %> to create a new tree.</p>

app/views/trees/new.html.erb
<h1>New tree</h1>
<%= form_for :tree, url: trees_path do |f| %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</p>
	<p>
		Initial data (brackets)<br/>
		<%= f.text_field :brackets %>
	</p>
	<p>
		<%= f.submit "Create" %>
	</p>
<% end %>